name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to JFrog Artifactory
      run: echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login hesterinc.jfrog.io -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

    - name: Pull Docker image
      run: docker pull hesterinc.jfrog.io/petclinic-docker-local/spring-petclinic:latest

    - name: Run Docker container
      run: docker run -d -p 8080:8080 hesterinc.jfrog.io/petclinic-docker-local/spring-petclinic:latest

    - name: Test the application
      run: |
        # Wait for the container to start
        sleep 30
        # Test the application (this is just an example, adjust as needed)
        curl --fail http://localhost:8080 || exit 1

    - name: Stop Docker container
      run: docker stop $(docker ps -q --filter ancestor=hesterinc.jfrog.io/petclinic-docker-local/spring-petclinic:latest)
